from math import *
print(2)
print(-2.5)
print(3+4)
print (3 ** 3)
print(3*4+5)
print(3*(4+5))
print(10%3)
my_num = -5
print(my_num)
print(str(my_num)+ " my favourite number")
print(abs(my_num))
print(pow(4,5))
print(max(5,6))
print(min(5,6))
print(round(3.7))
print(floor(3.7))
print(ceil(3.3))
print(sqrt(9))
